# render.yaml
services:
  - type: web
    name: autobot-backend
    env: java
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render
    plan: free