services:
  - type: web
    name: autobot-backend
    env: java
    buildCommand: "./mvnw -B -V -e -X -DtrimStackTrace=false -s .mvn/settings.xml -DskipTests package"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render
    plan: free

